name: RayTraceAntiXray
version: 1.14.0
main: com.vanillage.raytraceantixray.RayTraceAntiXray
description: Paper plugin for server-side async multithreaded ray tracing to hide ores that are exposed to air using Paper Anti-Xray engine-mode 1.
api-version: '1.20.6'
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
load: STARTUP
folia-supported: true